const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const COLOR_FIELDS = ["background", "gradientEnd", "heading", "text", "accent", "link", "button", "buttonText", "border", "overlay"];
const state = { pages: [], contentHtml: "", sourceHtml: "", sharedVideo: "", sections: {}, sectionColors: {}, uploadSettings: { maxUploadMb: 1024, recommendedImageMb: 30, recommendedVideoMb: 300 }, user: null, users: [], activity: [], ticker: { mode: "latest", customMessage: "" } };

async function request(url, options = {}) {
  let response;
  try { response = await fetch(url, { headers: { ...(options.body instanceof FormData ? {} : { "Content-Type": "application/json" }), ...(options.headers || {}) }, ...options }); }
  catch { throw new Error("Local Admin needs the LGC server. In VS Code Terminal, stop Live Server, run npm start, then open http://localhost:3000/admin."); }
  if (response.headers.get("X-LGC-Local-Server") !== "1") throw new Error("You opened this using Live Server. Stop Live Server, run npm start in the LGC folder, then open http://localhost:3000/admin.");
  const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || `The local server returned ${response.status}.`); return data;
}
function showMessage(target, message, success = false) { const element = $(target); element.textContent = message; element.classList.toggle("success", success); }
function showMessageFor(element, message, success = false) { element.textContent = message; element.classList.toggle("success", success); }
function escapeAttribute(value) { return String(value || "").replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;"); }
function normaliseHex(value) { return /^#[0-9a-fA-F]{6}$/.test(String(value || "")) ? String(value).toLowerCase() : ""; }
function humanize(value) { return String(value || "general").replace(/[-_]/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }

function fillPageMenus() { ["#contentPage", "#mediaPage", "#sourcePage"].forEach((selector) => { $(selector).innerHTML = state.pages.map((page) => `<option value="${page.file}">${page.label}</option>`).join(""); }); }
function renderOverview() {
  const stats = [[state.pages.length, "Editable pages", "data/pages"], [Object.keys(state.sections).length, "Visual segments", "section color code files"], [state.sharedVideo ? "1" : "0", "Shared video", "public/index.html"], [`${state.uploadSettings.maxUploadMb} MB`, "Upload allowance", "config.js"]];
  $("#overviewStats").innerHTML = stats.map(([value, label, detail]) => `<article class="overview-stat"><strong>${value}</strong><span>${label}</span><small>${detail}</small></article>`).join("");
}
function roleLabel(role) { return role === "master" ? "Master Admin" : "Editor"; }
function renderUserIdentity() { const pill = $(".local-pill"); if (state.user) pill.innerHTML = `<i></i> ${escapeAttribute(state.user.displayName)} · ${roleLabel(state.user.role)}`; }
function accountInputStatus() {
  const displayName = $("#newUserDisplayName").value.trim(); const username = $("#newUserUsername").value.trim(); const password = $("#newUserPassword").value;
  const usernameIsValid = /^[a-zA-Z0-9._-]{3,48}$/.test(username); const passwordIsValid = password.length >= 6; const valid = displayName.length >= 2 && usernameIsValid && passwordIsValid;
  $("#createEditorButton").disabled = !valid;
  $("#accountReadiness").textContent = valid ? "Ready to create this Editor account." : !displayName ? "Add the Editor’s display name." : !usernameIsValid ? "Use 3–48 letters, numbers, dots, underscores, or hyphens for the username." : "Use a temporary password with at least 6 characters.";
  $("#accountReadiness").classList.toggle("ready", valid); return { valid, displayName, username, password };
}

async function loadPage(page, type) { const data = await request(`/api/admin/page/${encodeURIComponent(page)}`); if (type === "content") { state.contentHtml = data.html; renderContentEditor(data.html); } if (type === "media") renderMediaManager(data.html, page); if (type === "source") { state.sourceHtml = data.html; $("#sourceEditor").value = data.html; } }
function sectionIdentity(node) {
  const section = node.closest("section");
  if (!section) return { id: "general", label: "General content" };
  const className = [...section.classList].find((item) => item.startsWith("chapter-"));
  const id = section.id || className || "general";
  return { id, label: section.getAttribute("aria-label") || (className ? humanize(className.replace("chapter-", "")) : humanize(id)) };
}
function editableNodes(documentNode) {
  return [...documentNode.querySelectorAll("h1,h2,h3,h4,p,li,a.btn,a.text-link,.tag,.eyebrow,.quote,.quote-attr")]
    .filter((node) => node.children.length === 0 && node.textContent.trim().length > 0)
    .filter((node) => !node.closest(".nav, .site-header, .site-footer"))
    .map((node) => ({ node, section: sectionIdentity(node) }));
}
function editableSections(documentNode) {
  return [...documentNode.querySelectorAll("section")]
    .map((node) => ({ node, section: sectionIdentity(node) }))
    .filter((entry, index, all) => entry.section.id !== "general" && all.findIndex((candidate) => candidate.section.id === entry.section.id) === index);
}
function segmentStyle(id) { if (/hero|intro|header/.test(id)) return "segment-hero"; if (/belief|academics|president|news|cta/.test(id)) return `segment-${id}`; return "segment-page"; }
function publicPreviewPath(page) { return page === "index.html" ? "/" : `/${encodeURIComponent(page)}`; }
function renderContentCanvas(documentNode) {
  const canvas = $("#contentCanvas"); const sections = editableSections(documentNode); const current = $("#contentSection").value;
  canvas.innerHTML = `<div class="live-layout-preview"><div class="live-layout-bar"><strong>Live ${escapeAttribute($("#contentPage").selectedOptions[0]?.textContent || "page")} layout</strong><a href="${publicPreviewPath($("#contentPage").value)}" target="_blank" rel="noreferrer">Open public page</a></div><iframe title="Live public website page preview" src="${publicPreviewPath($("#contentPage").value)}" loading="lazy"></iframe></div><div class="canvas-head"><strong>Choose a section to edit</strong><span>These controls follow the previewed page order.</span></div><div class="canvas-grid"><button type="button" class="canvas-segment canvas-all ${current === "all" ? "selected" : ""}" data-content-segment="all"><b>All page content</b><small>Show every editable section</small></button>${sections.map((entry) => `<button type="button" class="canvas-segment ${segmentStyle(entry.section.id)} ${current === entry.section.id ? "selected" : ""}" data-content-segment="${escapeAttribute(entry.section.id)}"><b>${escapeAttribute(entry.section.label)}</b><small>Click to edit this segment</small></button>`).join("")}</div>`;
  $$('[data-content-segment]').forEach((button) => button.addEventListener("click", () => { $("#contentSection").value = button.dataset.contentSegment; renderContentEditor(state.contentHtml); $("#contentForm").scrollIntoView({ behavior: "smooth", block: "start" }); }));
}
function renderContentEditor(html) {
  const documentNode = new DOMParser().parseFromString(html, "text/html"); const entries = editableNodes(documentNode); const selector = $("#contentSection"); const selected = selector.value || "all";
  const groups = [...new Map(entries.map((entry) => [entry.section.id, entry.section.label])).entries()]; selector.innerHTML = `<option value="all">All sections</option>${groups.map(([id, label]) => `<option value="${id}">${escapeAttribute(label)}</option>`).join("")}`; selector.value = groups.some(([id]) => id === selected) || selected === "all" ? selected : "all";
  const filtered = entries.filter((entry) => selector.value === "all" || entry.section.id === selector.value);
  const grouped = filtered.reduce((result, entry, index) => { const key = entry.section.id; if (!result[key]) result[key] = { label: entry.section.label, fields: [] }; result[key].fields.push({ entry, index: entries.indexOf(entry) }); return result; }, {});
  const sections = editableSections(documentNode); const visibility = sections.filter((entry) => selector.value === "all" || entry.section.id === selector.value);
  const visibilityControls = visibility.length ? `<section class="section-visibility"><header><span>Section visibility</span><small>Choose which page segments appear on the public website.</small></header><div>${visibility.map((entry) => `<label><input type="checkbox" data-section-visibility-index="${sections.indexOf(entry)}" ${entry.node.hidden ? "" : "checked"}> Show ${escapeAttribute(entry.section.label)}</label>`).join("")}</div></section>` : "";
  $("#contentForm").innerHTML = `${visibilityControls}${Object.entries(grouped).map(([id, group]) => `<section class="content-group"><header><span>${escapeAttribute(group.label)}</span><small>${id === "general" ? "General page copy" : "Section content"}</small></header>${group.fields.map(({ entry, index }) => `<label class="field"><small>${entry.node.tagName.toUpperCase()} · ${escapeAttribute(entry.section.label)}</small><textarea data-text-index="${index}">${escapeAttribute(entry.node.textContent.trim())}</textarea>${entry.node.matches("a[href]") ? `<span class="content-link-field"><small>CTA or text-link destination</small><input type="text" data-link-index="${index}" value="${escapeAttribute(entry.node.getAttribute("href") || "")}" aria-label="Link destination for ${escapeAttribute(entry.node.textContent.trim())}"></span>` : ""}</label>`).join("")}</section>`).join("")}` || "<p>No simple visible text fields were found. Use Source for structural changes.</p>";
  renderContentCanvas(documentNode);
}
function saveTextChanges() { const documentNode = new DOMParser().parseFromString(state.contentHtml, "text/html"); const nodes = editableNodes(documentNode); const sections = editableSections(documentNode); $$("[data-text-index]").forEach((field) => { const item = nodes[Number(field.dataset.textIndex)]; if (item) item.node.textContent = field.value; }); $$("[data-link-index]").forEach((field) => { const item = nodes[Number(field.dataset.linkIndex)]; if (item && item.node.matches("a[href]")) item.node.setAttribute("href", field.value.trim() || "#"); }); $$("[data-section-visibility-index]").forEach((field) => { const item = sections[Number(field.dataset.sectionVisibilityIndex)]; if (item) item.node.toggleAttribute("hidden", !field.checked); }); return request(`/api/admin/page/${encodeURIComponent($("#contentPage").value)}`, { method: "PUT", body: JSON.stringify({ html: "<!DOCTYPE html>\n" + documentNode.documentElement.outerHTML, changeType: "structured" }) }); }

function findMedia(html) { const documentNode = new DOMParser().parseFromString(html, "text/html"); const items = []; documentNode.querySelectorAll("img[src], video[poster], video source[src]").forEach((node) => { const attr = node.tagName === "VIDEO" ? "poster" : "src"; const original = node.getAttribute(attr); if (original && original.startsWith("assets/")) items.push({ original, type: node.tagName.toLowerCase() === "source" ? "video" : "image" }); }); return [...new Map(items.map((item) => [item.original, item])).values()]; }
function renderMediaManager(html, page) {
  const media = findMedia(html).filter((item) => item.type !== "video"); const { maxUploadMb } = state.uploadSettings;
  const sharedVideo = `<article class="media-item"><video muted controls src="/${state.sharedVideo}"></video><strong>Shared website video</strong><code>${state.sharedVideo || "No shared video selected"}</code><form data-shared-video><input type="file" accept="video/*" required><small class="upload-limit">Maximum: ${maxUploadMb} MB</small><button type="submit">Replace shared video</button><span class="message" role="status"></span></form></article>`;
  $("#mediaList").innerHTML = `${sharedVideo}${media.map((item, index) => `<article class="media-item"><img src="/${item.original}" alt="Current local media"><strong>Image ${index + 1}</strong><code>${item.original}</code><form data-media="${encodeURIComponent(item.original)}"><input type="file" accept="image/*" required><small class="upload-limit">Maximum: ${maxUploadMb} MB</small><button type="submit">Replace this file</button><span class="message" role="status"></span></form></article>`).join("")}`;
  $$('[data-shared-video]').forEach((form) => form.addEventListener("submit", async (event) => { event.preventDefault(); const message = form.querySelector(".message"); const file = form.querySelector("input[type=file]").files[0]; if (!file) return showMessageFor(message, "Choose a video file first."); if (file.size > maxUploadMb * 1024 * 1024) return showMessageFor(message, `This file is ${(file.size / 1024 / 1024).toFixed(1)} MB. The current limit is ${maxUploadMb} MB.`); const body = new FormData(); body.append("file", file); try { const result = await request("/api/admin/shared-video", { method: "POST", body }); state.sharedVideo = result.url; showMessageFor(message, "Saved to public/index.html. The video stays continuous during page changes.", true); await loadPage(page, "media"); } catch (error) { showMessageFor(message, error.message); } }));
  $$('[data-media]').forEach((form) => form.addEventListener("submit", async (event) => { event.preventDefault(); const message = form.querySelector(".message"); const file = form.querySelector("input[type=file]").files[0]; if (!file) return showMessageFor(message, "Choose an image file first."); if (file.size > maxUploadMb * 1024 * 1024) return showMessageFor(message, `This file is ${(file.size / 1024 / 1024).toFixed(1)} MB. The current limit is ${maxUploadMb} MB.`); const body = new FormData(); body.append("page", page); body.append("original", decodeURIComponent(form.dataset.media)); body.append("file", file); try { await request("/api/admin/media", { method: "POST", body }); showMessageFor(message, `Saved to data/pages/${page} and public/assets/uploads.`, true); await loadPage(page, "media"); } catch (error) { showMessageFor(message, error.message); } }));
}

function renderNewsEditor(items) { $("#newsForm").innerHTML = items.map((item, index) => `<article class="news-entry" data-news-index="${index}"><label>Date<input type="date" data-news-date value="${escapeAttribute(item.showDate)}"></label><label>Category<input data-news-type value="${escapeAttribute(item.type)}"></label><label>Title & message<input data-news-title value="${escapeAttribute(item.title)}"><textarea data-news-message>${escapeAttribute(item.message)}</textarea></label><button class="delete-news" type="button">Remove</button></article>`).join("") || "<p>No local announcements. Click Add announcement.</p>"; $$(".delete-news").forEach((button) => button.addEventListener("click", () => button.closest(".news-entry").remove())); }
async function loadNews() { renderNewsEditor(await request("/api/admin/news")); }
function collectNews() { return $$(".news-entry").map((entry) => ({ showDate: entry.querySelector("[data-news-date]").value, type: entry.querySelector("[data-news-type]").value, title: entry.querySelector("[data-news-title]").value, message: entry.querySelector("[data-news-message]").value })); }
async function loadTicker() { const ticker = await request("/api/admin/ticker-settings"); state.ticker = ticker; $(`[name='tickerMode'][value='${ticker.mode}']`).checked = true; $("#customTickerMessage").value = ticker.customMessage; $("#customTickerMessage").disabled = ticker.mode !== "custom"; }
function reportCategory(entry) { const text = `${entry.action || ""} ${entry.area || ""}`.toLowerCase(); if (/(user|password|signed|access)/.test(text)) return "access"; if (/media|video/.test(text)) return "media"; if (/news|ticker/.test(text)) return "news"; return "content"; }
function readableArea(entry) { if (entry.area) return entry.area; const category = reportCategory(entry); return category === "access" ? "Account access" : category === "media" ? "Media" : category === "news" ? "News & ticker" : "Website content"; }
function readableSource(entry) { if (entry.sourceFile) return entry.sourceFile; return entry.action === "Updated page" ? `data/pages/${entry.details}` : "Local website files"; }
function renderActivityReport() {
  const filter = $("#reportFilter").value; const all = state.activity || []; const activity = filter === "all" ? all : all.filter((entry) => reportCategory(entry) === filter);
  const participantCount = new Set(activity.map((entry) => entry.actor?.username).filter(Boolean)).size; const websiteChanges = activity.filter((entry) => reportCategory(entry) === "content").length;
  $("#reportSummary").innerHTML = `<article><strong>${activity.length}</strong><span>recorded changes</span></article><article><strong>${participantCount}</strong><span>people involved</span></article><article><strong>${websiteChanges}</strong><span>website updates</span></article>`;
  $("#reportCount").textContent = filter === "all" ? "Showing all records" : `Showing ${activity.length} matching record${activity.length === 1 ? "" : "s"}`;
  $("#activityList").innerHTML = activity.map((entry) => { const time = new Date(entry.time); const actor = entry.actor ? `${entry.actor.displayName || entry.actor.username} · ${roleLabel(entry.actor.role)}` : "System"; return `<article class="report-entry"><time class="report-time"><strong>${time.toLocaleDateString()}</strong><span>${time.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span></time><div class="report-main"><p class="report-area">${escapeAttribute(readableArea(entry))}</p><h3>${escapeAttribute(entry.action)}</h3><p>${escapeAttribute(entry.details || "No additional details recorded.")}</p></div><dl><div><dt>Changed by</dt><dd>${escapeAttribute(actor)}</dd></div><div><dt>Local file</dt><dd><code>${escapeAttribute(readableSource(entry))}</code></dd></div></dl></article>`; }).join("") || "<p class=empty-report>No matching local changes have been recorded yet.</p>";
}
async function renderActivity() { state.activity = await request("/api/admin/activity"); renderActivityReport(); }

function currentColorValues() { const values = Object.fromEntries(COLOR_FIELDS.map((key) => [key, $(`[data-color-code='${key}']`).value])); values.gradientEnabled = $("#gradientEnabled").checked; values.visible = $("#sectionVisible").checked; values.overlayOpacity = Number($("#overlayOpacity").value) / 100; values.paddingY = Number($("#paddingY").value); return values; }
function renderColorPreview() { const values = currentColorValues(); const preview = $("#sectionColorPreview"); ["background", "text", "accent", "button"].forEach((field) => { const value = normaliseHex(values[field]); if (value) preview.style.setProperty(`--preview-${field}`, value); }); preview.style.setProperty("--preview-heading", normaliseHex(values.heading) || values.text); }
function renderSectionCanvas() { const canvas = $("#designCanvas"); const selected = $("#colorSection").value; canvas.innerHTML = `<div class="live-layout-preview"><div class="live-layout-bar"><strong>Live public website layout</strong><a href="/" target="_blank" rel="noreferrer">Open public page</a></div><iframe title="Live public website design preview" src="/" loading="lazy"></iframe></div><div class="canvas-head"><strong>Choose an area to style</strong><span>Use the real website preview above as your visual reference.</span></div><div class="canvas-grid">${Object.entries(state.sections).map(([key, section]) => `<button type="button" class="canvas-segment ${segmentStyle(key)} ${selected === key ? "selected" : ""}" data-design-segment="${key}"><b>${escapeAttribute(section.label)}</b><small>${key === "header" ? "Navigation area" : key === "hero" ? "Shared video introduction" : "Style this section"}</small></button>`).join("")}</div>`; $$('[data-design-segment]').forEach((button) => button.addEventListener("click", () => { $("#colorSection").value = button.dataset.designSegment; renderColorEditor(); $(".design-workbench").scrollIntoView({ behavior: "smooth", block: "start" }); })); }
function renderColorEditor() { const key = $("#colorSection").value; const colors = state.sectionColors[key]; if (!colors) return; COLOR_FIELDS.forEach((field) => { $(`[data-color-picker='${field}']`).value = colors[field]; $(`[data-color-code='${field}']`).value = colors[field]; }); $("#gradientEnabled").checked = Boolean(colors.gradientEnabled); $("#sectionVisible").checked = colors.visible !== false; $("#overlayOpacity").value = Math.round(Number(colors.overlayOpacity ?? .72) * 100); $("#overlayOpacityValue").textContent = `${$("#overlayOpacity").value}%`; $("#paddingY").value = colors.paddingY || 0; $("#sectionColorPreview").querySelector("strong").textContent = state.sections[key]?.label || colors.label; $$('[data-design-segment]').forEach((button) => button.classList.toggle("selected", button.dataset.designSegment === key)); renderColorPreview(); }
async function loadSectionColors() { const data = await request("/api/admin/section-colors"); state.sections = data.sections; state.sectionColors = data.colors; const select = $("#colorSection"); const selected = select.value || "header"; select.innerHTML = Object.entries(state.sections).map(([key, section]) => `<option value="${key}">${section.label}</option>`).join(""); select.value = state.sections[selected] ? selected : Object.keys(state.sections)[0]; renderSectionCanvas(); renderColorEditor(); renderOverview(); }

function renderUsers(users) {
  state.users = users; $("#usersList").innerHTML = users.map((user) => { const master = user.role === "master"; return `<article class="user-card ${master ? "master-account" : ""}" data-user-id="${user.id}"><header><div><strong>${escapeAttribute(user.displayName)}</strong><span>@${escapeAttribute(user.username)}</span></div><p class="access-badge">${roleLabel(user.role)}</p></header><label class="user-name-field">Display name<input data-user-display-name value="${escapeAttribute(user.displayName)}" ${master ? "readonly" : ""}></label><div class="account-meta"><span class="account-state ${user.enabled ? "enabled" : "disabled"}">${user.enabled ? "Active" : "Disabled"}</span><small>Created ${new Date(user.createdAt).toLocaleDateString()}</small></div>${master ? "<p class=account-note>This protected account controls all local users and reports.</p>" : `<label class="switch-label"><input data-user-enabled type="checkbox" ${user.enabled ? "checked" : ""}> Allow this Editor to sign in and edit the website</label>`}<div class="user-actions">${master ? "" : "<button type=button data-save-user>Save account changes</button>"}<button type="button" class="quiet" data-copy-user>Copy sign-in name</button><button type="button" class="quiet" data-toggle-reset>Set new password</button>${master ? "" : `<button type="button" class="danger" data-remove-user>Remove</button>`}</div><div class="inline-password-reset" hidden><label>New password<input type="password" data-reset-password minlength="6" placeholder="At least 6 characters"></label><button type="button" data-confirm-reset disabled>Save new password</button><span class="message" role="status"></span></div></article>`; }).join("");
  $$('[data-save-user]').forEach((button) => button.addEventListener("click", async () => { const card = button.closest(".user-card"); try { await request(`/api/admin/users/${card.dataset.userId}`, { method: "PUT", body: JSON.stringify({ displayName: card.querySelector("[data-user-display-name]").value.trim(), enabled: card.querySelector("[data-user-enabled]").checked }) }); showMessage("#userMessage", "Editor account changes saved.", true); await loadUsers(); } catch (error) { showMessage("#userMessage", error.message); } }));
  $$('[data-copy-user]').forEach((button) => button.addEventListener("click", async () => { const card = button.closest(".user-card"); const username = card.querySelector("header span").textContent.replace(/^@/, ""); try { await navigator.clipboard.writeText(username); showMessage("#userMessage", `Copied ${username}. Share the temporary password separately.`, true); } catch { showMessage("#userMessage", `Sign-in username: ${username}`, true); } }));
  $$('[data-toggle-reset]').forEach((button) => button.addEventListener("click", () => { const reset = button.closest(".user-card").querySelector(".inline-password-reset"); reset.hidden = !reset.hidden; if (!reset.hidden) reset.querySelector("[data-reset-password]").focus(); }));
  $$('[data-reset-password]').forEach((input) => input.addEventListener("input", () => { input.closest(".inline-password-reset").querySelector("[data-confirm-reset]").disabled = input.value.length < 6; }));
  $$('[data-confirm-reset]').forEach((button) => button.addEventListener("click", async () => { const card = button.closest(".user-card"); const reset = button.closest(".inline-password-reset"); const password = reset.querySelector("[data-reset-password]").value; const message = reset.querySelector(".message"); if (password.length < 6) return showMessageFor(message, "Use at least 6 characters."); button.disabled = true; try { await request(`/api/admin/users/${card.dataset.userId}/password`, { method: "PUT", body: JSON.stringify({ password }) }); showMessageFor(message, "Password saved.", true); reset.querySelector("[data-reset-password]").value = ""; setTimeout(() => { reset.hidden = true; }, 850); } catch (error) { showMessageFor(message, error.message); button.disabled = false; } }));
  $$('[data-remove-user]').forEach((button) => button.addEventListener("click", async () => { const card = button.closest(".user-card"); if (!window.confirm(`Remove ${card.querySelector("header strong").textContent}? This cannot be undone.`)) return; try { await request(`/api/admin/users/${card.dataset.userId}`, { method: "DELETE" }); showMessage("#userMessage", "Local user removed.", true); await loadUsers(); } catch (error) { showMessage("#userMessage", error.message); } }));
}
async function loadUsers() { if (state.user?.role !== "master") return; renderUsers(await request("/api/admin/users")); }

function activateTab(name) {
  if (["users", "activity"].includes(name) && state.user?.role !== "master") return;
  $$(".tab").forEach((button) => button.classList.toggle("active", button.dataset.tab === name));
  ["overview", "content", "media", "design", "news", "users", "source", "activity"].forEach((tab) => $(`#${tab}Panel`).hidden = tab !== name);
  if (name === "activity") renderActivity().catch((error) => showMessage("#exportMessage", error.message));
  if (name === "news") Promise.all([loadNews(), loadTicker()]).catch((error) => showMessage("#newsMessage", error.message));
  if (name === "design") loadSectionColors().catch((error) => showMessage("#colorMessage", error.message));
  if (name === "users") loadUsers().catch((error) => showMessage("#userMessage", error.message));
}

async function openStudio(user) {
  const [pages, uploadSettings, sharedVideo] = await Promise.all([request("/api/admin/pages"), request("/api/admin/upload-settings"), request("/api/admin/shared-video")]); state.user = user || state.user; state.pages = pages; state.uploadSettings = uploadSettings; state.sharedVideo = sharedVideo.source; fillPageMenus(); renderUserIdentity(); $$(".master-tab").forEach((button) => button.hidden = state.user?.role !== "master"); $$(".master-tab-group").forEach((group) => group.hidden = state.user?.role !== "master"); $("#loginCard").hidden = true; $("#studio").hidden = false; await Promise.all([loadPage($("#contentPage").value, "content"), loadPage($("#mediaPage").value, "media"), loadPage($("#sourcePage").value, "source"), loadSectionColors()]);
}

$("#loginForm").addEventListener("submit", async (event) => { event.preventDefault(); try { const result = await request("/api/admin/login", { method: "POST", body: JSON.stringify({ username: $("#username").value, password: $("#password").value }) }); await openStudio(result.user); } catch (error) { showMessage("#loginMessage", error.message); } });
$("#logoutButton").addEventListener("click", async () => { await request("/api/admin/logout", { method: "POST" }); location.reload(); });
$$(".tab").forEach((button) => button.addEventListener("click", () => activateTab(button.dataset.tab)));
$$("[data-open-tab]").forEach((button) => button.addEventListener("click", () => activateTab(button.dataset.openTab)));
$("#contentPage").addEventListener("change", () => loadPage($("#contentPage").value, "content")); $("#contentSection").addEventListener("change", () => renderContentEditor(state.contentHtml)); $("#mediaPage").addEventListener("change", () => loadPage($("#mediaPage").value, "media")); $("#sourcePage").addEventListener("change", () => loadPage($("#sourcePage").value, "source"));
$("#saveContent").addEventListener("click", async () => { try { const page = $("#contentPage").value; await saveTextChanges(); showMessage("#contentMessage", `Saved structured content to data/pages/${page}.`, true); await loadPage(page, "content"); } catch (error) { showMessage("#contentMessage", error.message); } });
$("#saveSource").addEventListener("click", async () => { try { const page = $("#sourcePage").value; await request(`/api/admin/page/${encodeURIComponent(page)}`, { method: "PUT", body: JSON.stringify({ html: $("#sourceEditor").value, changeType: "source" }) }); showMessage("#sourceMessage", `Saved directly to data/pages/${page}.`, true); } catch (error) { showMessage("#sourceMessage", error.message); } });
$("#addNews").addEventListener("click", () => { const existing = collectNews(); existing.unshift({ showDate: new Date().toISOString().slice(0, 10), type: "Announcement", title: "New announcement", message: "Add announcement details here." }); renderNewsEditor(existing); });
$("#saveNews").addEventListener("click", async () => { try { await request("/api/admin/news", { method: "PUT", body: JSON.stringify({ news: collectNews() }) }); showMessage("#newsMessage", "Saved to public/data/news.json. The automatic ticker uses the newest three titles.", true); } catch (error) { showMessage("#newsMessage", error.message); } });
$("#tickerForm").addEventListener("submit", async (event) => { event.preventDefault(); const mode = $("[name='tickerMode']:checked").value; try { await request("/api/admin/ticker-settings", { method: "PUT", body: JSON.stringify({ mode, customMessage: $("#customTickerMessage").value }) }); showMessage("#tickerMessage", mode === "custom" ? "Custom marquee saved to data/ticker-settings.json." : "Ticker set to the latest three news titles.", true); await loadTicker(); } catch (error) { showMessage("#tickerMessage", error.message); } });
$$('[name="tickerMode"]').forEach((input) => input.addEventListener("change", () => { $("#customTickerMessage").disabled = $("[name='tickerMode']:checked").value !== "custom"; }));
$("#exportButton").addEventListener("click", async () => { try { const result = await request("/api/admin/export", { method: "POST" }); showMessage("#exportMessage", `Export copy created in ${result.folder}`, true); await renderActivity(); } catch (error) { showMessage("#exportMessage", error.message); } });
$("#colorSection").addEventListener("change", renderColorEditor);
$("#reportFilter").addEventListener("change", renderActivityReport);
$$("[data-color-picker]").forEach((picker) => picker.addEventListener("input", () => { const key = picker.dataset.colorPicker; $(`[data-color-code='${key}']`).value = picker.value; renderColorPreview(); }));
$$("[data-color-code]").forEach((input) => input.addEventListener("input", () => { const value = normaliseHex(input.value); if (value) $(`[data-color-picker='${input.dataset.colorCode}']`).value = value; renderColorPreview(); }));
$("#overlayOpacity").addEventListener("input", () => { $("#overlayOpacityValue").textContent = `${$("#overlayOpacity").value}%`; });
$("#colorForm").addEventListener("submit", async (event) => { event.preventDefault(); const key = $("#colorSection").value; const colors = currentColorValues(); if (!COLOR_FIELDS.every((field) => normaliseHex(colors[field]))) return showMessage("#colorMessage", "Enter complete hex codes such as #064d22 for every color field."); try { await request("/api/admin/section-colors", { method: "PUT", body: JSON.stringify({ key, colors }) }); showMessage("#colorMessage", "Saved advanced style codes to data/section-colors.json and public/css/section-colors.css.", true); await loadSectionColors(); } catch (error) { showMessage("#colorMessage", error.message); } });
$("#resetColors").addEventListener("click", async () => { try { await request("/api/admin/section-colors/reset", { method: "POST", body: JSON.stringify({ key: $("#colorSection").value }) }); showMessage("#colorMessage", "Restored the LGC default codes in both local source files.", true); await loadSectionColors(); } catch (error) { showMessage("#colorMessage", error.message); } });
[$("#newUserDisplayName"), $("#newUserUsername"), $("#newUserPassword")].forEach((input) => input.addEventListener("input", accountInputStatus));
$("#toggleNewUserPassword").addEventListener("click", () => { const input = $("#newUserPassword"); const showing = input.type === "text"; input.type = showing ? "password" : "text"; $("#toggleNewUserPassword").textContent = showing ? "Show" : "Hide"; });
$("#createUserForm").addEventListener("submit", async (event) => { event.preventDefault(); const form = event.currentTarget; const account = accountInputStatus(); if (!account.valid) return showMessage("#userMessage", "Complete the account details before creating this Editor."); const button = $("#createEditorButton"); button.disabled = true; button.textContent = "Creating account…"; try { await request("/api/admin/users", { method: "POST", body: JSON.stringify(account) }); form.reset(); accountInputStatus(); showMessage("#userMessage", `Editor account @${account.username} was created. Share the temporary password privately.`, true); await loadUsers(); } catch (error) { showMessage("#userMessage", error.message); } finally { button.textContent = "Create Editor account"; accountInputStatus(); } });

request("/api/admin/status").then((status) => status.authenticated && openStudio(status.user)).catch(() => {});
